import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '../styles/globals.css';

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

// export const metadata: Metadata = {
//   title: 'Uptask',
// };

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang='en'>
        <body
          className={`${poppins.variable} ut-teal antialiased`}
          style={
            {
              '--theme-main-color': '#0f9d9f',
              '--theme-main-color-rgb': '15, 157, 159',
              '--theme-main-color-dark': '#0b787a',
              '--theme-main-color-light': '#40ebed',
            } as React.CSSProperties
          }
        >
          {children}
        </body>
      </html>
    </>
  );
}
